manifest:
  version: "0.13"
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: RobertoPeralCastro
      url-base: https://github.com/RobertoPeralCastro
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      clone-depth: 1
    - name: eyelash_sofle
      remote: RobertoPeralCastro
      revision: main
      path: eyelash_sofle
  self:
    path: config
